# Generated by Django 2.2.12 on 2020-05-05 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Faculty'),
        ),
        migrations.AddConstraint(
            model_name='scheduleitem',
            constraint=models.UniqueConstraint(fields=('title', 'start_time', 'schedule_day', 'teacher'), name='title_start_time_schedule_day_teacher'),
        ),
        migrations.AddConstraint(
            model_name='scheduleitem',
            constraint=models.UniqueConstraint(fields=('title', 'end_time', 'schedule_day', 'teacher'), name='title_end_time_schedule_day_teacher'),
        ),
        migrations.AddConstraint(
            model_name='scheduleitem',
            constraint=models.UniqueConstraint(fields=('start_time', 'schedule_day'), name='start_time_schedule_day'),
        ),
        migrations.AddConstraint(
            model_name='scheduleitem',
            constraint=models.UniqueConstraint(fields=('end_time', 'schedule_day'), name='end_time_schedule_day'),
        ),
    ]
