# Generated by Django 2.2.12 on 2020-05-07 17:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200505_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teaching_subject',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
